- name: "Copy the Compiled backend Files to EC2 instance"
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu

- name: "unarchive the dist directory"
  unarchive:
    src: /home/ubuntu/backend.tar.gz
    dest: /home/ubuntu
    copy: no

- name: "Install Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
- name: "Run the backend app"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls